//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class HRMSEntities : DbContext
    {
        public HRMSEntities()
            : base("name=HRMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Document> tbl_Document { get; set; }
        public virtual DbSet<tbl_login> tbl_login { get; set; }
        public virtual DbSet<tbl_usertype> tbl_usertype { get; set; }
        public virtual DbSet<tbl_dept> tbl_dept { get; set; }
        public virtual DbSet<tbl_Employee_type> tbl_Employee_type { get; set; }
        public virtual DbSet<tbl_sub_dept> tbl_sub_dept { get; set; }
        public virtual DbSet<tbl_Employee_status> tbl_Employee_status { get; set; }
        public virtual DbSet<tbl_job_descrion> tbl_job_descrion { get; set; }
        public virtual DbSet<tbl_leave_type> tbl_leave_type { get; set; }
        public virtual DbSet<tbl_salary_components> tbl_salary_components { get; set; }
        public virtual DbSet<tbl_Employe> tbl_Employe { get; set; }
        public virtual DbSet<tbl_leaving_policy> tbl_leaving_policy { get; set; }
        public virtual DbSet<tbl_emp_grade> tbl_emp_grade { get; set; }
        public virtual DbSet<tbl_employee_conectivity> tbl_employee_conectivity { get; set; }
        public virtual DbSet<tbl_emp_attendance> tbl_emp_attendance { get; set; }
        public virtual DbSet<tbl_emp_time_set> tbl_emp_time_set { get; set; }
        public virtual DbSet<tbl_employee_salary> tbl_employee_salary { get; set; }
        public virtual DbSet<tbl_loanpaidemp> tbl_loanpaidemp { get; set; }
        public virtual DbSet<tbl_world_country> tbl_world_country { get; set; }
        public virtual DbSet<tbl_salary_detuction_policy> tbl_salary_detuction_policy { get; set; }
        public virtual DbSet<tbl_salary> tbl_salary { get; set; }
        public virtual DbSet<tbl_employeeleave> tbl_employeeleave { get; set; }
        public virtual DbSet<tbl_holiday> tbl_holiday { get; set; }
        public virtual DbSet<tbl_holidays> tbl_holidays { get; set; }
        public virtual DbSet<tbl_emp_holiday> tbl_emp_holiday { get; set; }
        public virtual DbSet<tbl_noti> tbl_noti { get; set; }
        public virtual DbSet<tbl_email_server> tbl_email_server { get; set; }
    
        public virtual ObjectResult<SP_Employe_report_Result> SP_Employe_report()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Employe_report_Result>("SP_Employe_report");
        }
    
        public virtual ObjectResult<SP_Employe_report1_Result> SP_Employe_report1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Employe_report1_Result>("SP_Employe_report1");
        }
    
        public virtual ObjectResult<SP_Employe_report2_Result> SP_Employe_report2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Employe_report2_Result>("SP_Employe_report2");
        }
    }
}
