//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_salary
    {
        public long id { get; set; }
        public long fk_emp_id { get; set; }
        public string salary_month { get; set; }
        public string salary_year { get; set; }
        public Nullable<double> stat_bonus { get; set; }
        public double gross_earning_amount { get; set; }
        public double gross_deduction_amount { get; set; }
        public double net_pay { get; set; }
        public long inserted_by { get; set; }
        public string slip_url { get; set; }
    }
}
