//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Employe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Employe()
        {
            this.tbl_employee_salary = new HashSet<tbl_employee_salary>();
            this.tbl_loanpaidemp = new HashSet<tbl_loanpaidemp>();
        }
    
        public long id { get; set; }
        public string EmployeeCode { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string CNIC { get; set; }
        public string FatherFullName { get; set; }
        public string FatherCNIC { get; set; }
        public string Nationality { get; set; }
        public Nullable<System.DateTime> Dateofbirth { get; set; }
        public string Gender { get; set; }
        public string MaritalStatus { get; set; }
        public string Accomodation { get; set; }
        public string ResidenceAddress { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string MobilePhone { get; set; }
        public string WorkPhone { get; set; }
        public string WorkEmail { get; set; }
        public string PersonalEmail { get; set; }
        public string HomeAddress1 { get; set; }
        public string HomeAddress2 { get; set; }
        public string EmergencyContactName { get; set; }
        public string EmergencyRelation { get; set; }
        public string EmergencyHomePhone { get; set; }
        public string EmergencyWorkPhone { get; set; }
        public string EmergencyMobile { get; set; }
        public Nullable<System.DateTime> inserteddatetime { get; set; }
        public Nullable<bool> status { get; set; }
        public string img_url { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_employee_salary> tbl_employee_salary { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_loanpaidemp> tbl_loanpaidemp { get; set; }
    }
}
