//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_loanpaidemp
    {
        public long loan_id { get; set; }
        public long emp_id { get; set; }
        public long loan_amount { get; set; }
        public int payabletime_in_month { get; set; }
        public int remaining_loan_amount { get; set; }
        public string applied_from { get; set; }
        public string Status { get; set; }
        public Nullable<long> payable_amount_per_month { get; set; }
        public Nullable<int> remaining_month_payable { get; set; }
    
        public virtual tbl_Employe tbl_Employe { get; set; }
    }
}
