//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_employee_salary
    {
        public long id { get; set; }
        public Nullable<long> fk_employee_id { get; set; }
        public Nullable<long> amount { get; set; }
        public Nullable<bool> status { get; set; }
        public string salary_component { get; set; }
    
        public virtual tbl_Employe tbl_Employe { get; set; }
    }
}
