//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_job_descrion
    {
        public long id { get; set; }
        public string Designation { get; set; }
        public string Job_description { get; set; }
        public Nullable<decimal> salary_range_min { get; set; }
        public Nullable<decimal> salary_range_max { get; set; }
        public Nullable<bool> status { get; set; }
    }
}
