//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_leaving_policy
    {
        public long id { get; set; }
        public string Leavepolicy { get; set; }
        public Nullable<decimal> col_1 { get; set; }
        public Nullable<decimal> col_2 { get; set; }
        public Nullable<decimal> col_3 { get; set; }
        public Nullable<decimal> col_4 { get; set; }
        public Nullable<decimal> col_5 { get; set; }
        public Nullable<decimal> col_6 { get; set; }
        public Nullable<decimal> col_7 { get; set; }
        public string Note { get; set; }
        public Nullable<bool> status { get; set; }
    }
}
