
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CRM
{

using System;
    using System.Collections.Generic;
    
public partial class tbl_leads
{

    public int Id { get; set; }

    public string Name { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public string Status { get; set; }

    public string Others { get; set; }

    public int SourceId { get; set; }

    public int LeadStatusId { get; set; }

    public int AssignUserId { get; set; }

}

}
