//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_holidays
    {
        public int id { get; set; }
        public Nullable<bool> weekly { get; set; }
        public Nullable<bool> yearly { get; set; }
        public Nullable<bool> one_time { get; set; }
        public Nullable<int> holiday_day { get; set; }
        public Nullable<System.DateTime> holiday_date { get; set; }
        public int grade_id { get; set; }
    }
}
