//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_employee_conectivity
    {
        public long id { get; set; }
        public Nullable<long> employe_fk { get; set; }
        public Nullable<long> Dept_fk { get; set; }
        public Nullable<long> SubDept_fk { get; set; }
        public Nullable<long> jobtitle_fk { get; set; }
        public Nullable<System.DateTime> Joindate { get; set; }
        public Nullable<System.DateTime> Confirmationdate { get; set; }
        public Nullable<long> grade_fk { get; set; }
        public Nullable<long> Supervisor_fk { get; set; }
        public Nullable<System.DateTime> TerminationDate { get; set; }
        public string Notes { get; set; }
        public Nullable<long> fk_bank_details { get; set; }
        public Nullable<long> Emplyeestatus_fk { get; set; }
        public Nullable<System.DateTime> ContractStartDate { get; set; }
        public Nullable<System.DateTime> ContractEndDate { get; set; }
        public Nullable<System.DateTime> inserteddatetime { get; set; }
        public Nullable<long> insertedby { get; set; }
        public Nullable<System.DateTime> updatedatetime { get; set; }
        public Nullable<long> updateby { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<long> userid_fk { get; set; }
    }
}
