//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_emp_time_set
    {
        public long id { get; set; }
        public Nullable<System.TimeSpan> timeIN { get; set; }
        public Nullable<System.TimeSpan> timeout { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<long> fk_grade_id { get; set; }
    }
}
