//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_emp_attendance
    {
        public long id { get; set; }
        public Nullable<long> fk_emp { get; set; }
        public Nullable<long> fk_emp_time_set { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<System.TimeSpan> time { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> inserteddatetime { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<bool> late { get; set; }
        public Nullable<double> working_hours { get; set; }
        public Nullable<bool> leave { get; set; }
        public Nullable<int> month { get; set; }
        public Nullable<int> year { get; set; }
    }
}
