//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_noti
    {
        public Nullable<long> fk_userid { get; set; }
        public string noti_content { get; set; }
        public Nullable<bool> del_status { get; set; }
        public Nullable<bool> read_status { get; set; }
        public long id { get; set; }
    }
}
