//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_login
    {
        public long id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string Email { get; set; }
        public Nullable<long> User_type { get; set; }
        public string Desgination { get; set; }
        public string Contact { get; set; }
        public Nullable<bool> Active_status { get; set; }
    
        public virtual tbl_usertype tbl_usertype { get; set; }
    }
}
