//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Document
    {
        public long id { get; set; }
        public string documentName { get; set; }
        public string DocumentURL { get; set; }
        public Nullable<long> UserType { get; set; }
        public Nullable<long> Parent { get; set; }
        public Nullable<long> Sequence { get; set; }
        public string icon { get; set; }
        public string Application_type { get; set; }
    }
}
