//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_salary_detuction_policy
    {
        public long id { get; set; }
        public string late_detuction { get; set; }
        public string absent_detuction { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<long> fk_emp_grade { get; set; }
    }
}
